#!/usr/bin/env python3
"""Convert the MIT-0 AWS RoboMaker warehouse assets for MuJoCo.

MuJoCo reads STL, OBJ and MSH; the upstream assets are COLLADA. This converts
the visual meshes CLAVE dresses its scene with, scales them from centimeters to
meters, and copies the two textures, writing everything under `assets/warehouse/`.

The output is generated rather than committed, for the same reason a dataset is:
it is derived from bytes a submodule already pins, and committing it would put a
second copy in the history that no digest describes. The world builds without it
and says so.

Run it once after checking out the submodule::

    git submodule update --init third_party/aws-robomaker-small-warehouse-world
    python scripts/import_warehouse_assets.py
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "third_party" / "aws-robomaker-small-warehouse-world" / "models"
OUT = ROOT / "assets" / "warehouse"

CENTIMETERS_TO_METERS = 0.01
"""The upstream meshes are authored in centimeters."""

MESHES = {
    "shelf.obj": "aws_robomaker_warehouse_ShelfD_01",
    "shelf_e.obj": "aws_robomaker_warehouse_ShelfE_01",
    "trash_can.obj": "aws_robomaker_warehouse_TrashCanC_01",
    "pallet_jack.obj": "aws_robomaker_warehouse_PalletJackB_01",
    "bucket.obj": "aws_robomaker_warehouse_Bucket_01",
}
"""What CLAVE dresses its scene with, and where each comes from upstream."""

TEXTURES = {
    "ground.png": (
        "aws_robomaker_warehouse_GroundB_01",
        "aws_robomaker_warehouse_GroundB_01.png",
    ),
    "wall.png": (
        "aws_robomaker_warehouse_WallB_01",
        "aws_robomaker_warehouse_WallB_01.png",
    ),
}
"""The two surfaces that carry a texture rather than a mesh."""


def convert(name: str, model: str) -> tuple[str, tuple[float, float, float]]:
    """Convert one visual mesh to OBJ in meters.

    Args:
        name: Output file name.
        model: Upstream model directory.

    Returns:
        The output name and the converted extents, for the manifest.

    Raises:
        FileNotFoundError: If the upstream mesh is absent.
    """
    import trimesh

    candidates = sorted((SOURCE / model / "meshes").glob("*visual*.DAE"))
    if not candidates:
        raise FileNotFoundError(f"{model} has no visual mesh")
    mesh = trimesh.load(candidates[0], force="mesh")
    mesh.apply_scale(CENTIMETERS_TO_METERS)
    # Origin at the footprint centre and the base on the floor, so a pose in the
    # world configuration names where the prop stands rather than where its
    # author happened to put the origin.
    mesh.apply_translation(
        [-mesh.bounds[:, 0].mean(), -mesh.bounds[:, 1].mean(), -mesh.bounds[0][2]]
    )
    (OUT / "meshes").mkdir(parents=True, exist_ok=True)
    mesh.export(OUT / "meshes" / name)
    extents = tuple(round(float(value), 3) for value in mesh.extents)
    return name, (extents[0], extents[1], extents[2])


def main() -> int:
    """Convert every mesh and copy every texture.

    Returns:
        A process exit code.
    """
    if not SOURCE.is_dir():
        print(
            "the warehouse submodule is not checked out. Run:\n"
            "  git submodule update --init "
            "third_party/aws-robomaker-small-warehouse-world",
            file=sys.stderr,
        )
        return 1
    try:
        import trimesh  # noqa: F401
    except ImportError:
        print(
            'trimesh and pycollada are needed. Run: uv pip install "clave[assets]"',
            file=sys.stderr,
        )
        return 1

    rows = [convert(name, model) for name, model in sorted(MESHES.items())]
    (OUT / "textures").mkdir(parents=True, exist_ok=True)
    for name, (model, upstream) in sorted(TEXTURES.items()):
        source = SOURCE / model / "materials" / "textures" / upstream
        if not source.is_file():
            print(f"  missing texture {source}", file=sys.stderr)
            continue
        shutil.copyfile(source, OUT / "textures" / name)

    manifest = [
        "# Imported AWS RoboMaker warehouse assets",
        "",
        "Generated by `scripts/import_warehouse_assets.py` from the submodule at",
        "`third_party/aws-robomaker-small-warehouse-world`, MIT-0.",
        "",
        "Nothing here is committed. The world builds without it and says so.",
        "",
        "| File | Upstream model | Extents (m) |",
        "| --- | --- | --- |",
    ]
    for name, extents in rows:
        model = MESHES[name]
        size = " x ".join(f"{value:.3f}" for value in extents)
        manifest.append(f"| `meshes/{name}` | `{model}` | {size} |")
    for name, (model, _) in sorted(TEXTURES.items()):
        manifest.append(f"| `textures/{name}` | `{model}` | texture |")
    (OUT / "IMPORTED.md").write_text("\n".join(manifest) + "\n")

    print(f"  wrote {len(rows)} meshes and {len(TEXTURES)} textures to {OUT}")
    for name, extents in rows:
        print(f"    {name:18s} {extents[0]:.3f} x {extents[1]:.3f} x {extents[2]:.3f} m")
    return 0


if __name__ == "__main__":  # pragma: no cover - a one-off import step
    raise SystemExit(main())
